<div class="content-index">

    <h1>Bienvenue sur POEC CHAT !</h1>

    <!--    Formulaire de connexion-->
    
    <div class="form_connexion">

        <form action="?page=index" method="post">
            
            <label for="pseudo">Pseudo</label><br/>
            <input type="text" name="pseudo" id="pseudo" /><br/>
            <label for="message">Mot de passe</label><br/> 
            <input type="password" name="pass" id="pass" /><br/>

            <input type="submit" value="valider" />

        </form>
        
        
    </div>
</div>

