<?php include 'Controllers/'.$_GET['page'].'.php'; ?> 
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="Theme/css/style.css">
        <title>Chat</title>
    </head>
    
    <body>  
        <?php include 'Views/'.$_GET['page'].'.phtml'; ?> 
    </body>
    
    <script src="Theme/js/jquery/dist/jquery.min.js"></script>
    <script src="Theme/js/script.js"></script>
</html>

